knpu_oauth2_client:
    clients:
        github:
            # this will be one of the supported types
            type: github
            client_id: '%env(OAUTH_GITHUB_ID)%'
            client_secret: '%env(OAUTH_GITHUB_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: connect_github_check
      